/*
Сервис баннеров

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BannerGetRequest struct for BannerGetRequest
type BannerGetRequest struct {
	// Идентификаторы тэгов
	TagIds []int32 `json:"tag_ids,omitempty"`
	// Идентификатор фичи
	FeatureId *int32 `json:"feature_id,omitempty"`
	// Содержимое баннера
	Content map[string]interface{} `json:"content,omitempty"`
	// Флаг активности баннера
	IsActive *bool `json:"is_active,omitempty"`
}

// NewBannerGetRequest instantiates a new BannerGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBannerGetRequest() *BannerGetRequest {
	this := BannerGetRequest{}
	return &this
}

// NewBannerGetRequestWithDefaults instantiates a new BannerGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBannerGetRequestWithDefaults() *BannerGetRequest {
	this := BannerGetRequest{}
	return &this
}

// GetTagIds returns the TagIds field value if set, zero value otherwise.
func (o *BannerGetRequest) GetTagIds() []int32 {
	if o == nil || o.TagIds == nil {
		var ret []int32
		return ret
	}
	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BannerGetRequest) GetTagIdsOk() ([]int32, bool) {
	if o == nil || o.TagIds == nil {
		return nil, false
	}
	return o.TagIds, true
}

// HasTagIds returns a boolean if a field has been set.
func (o *BannerGetRequest) HasTagIds() bool {
	if o != nil && o.TagIds != nil {
		return true
	}

	return false
}

// SetTagIds gets a reference to the given []int32 and assigns it to the TagIds field.
func (o *BannerGetRequest) SetTagIds(v []int32) {
	o.TagIds = v
}

// GetFeatureId returns the FeatureId field value if set, zero value otherwise.
func (o *BannerGetRequest) GetFeatureId() int32 {
	if o == nil || o.FeatureId == nil {
		var ret int32
		return ret
	}
	return *o.FeatureId
}

// GetFeatureIdOk returns a tuple with the FeatureId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BannerGetRequest) GetFeatureIdOk() (*int32, bool) {
	if o == nil || o.FeatureId == nil {
		return nil, false
	}
	return o.FeatureId, true
}

// HasFeatureId returns a boolean if a field has been set.
func (o *BannerGetRequest) HasFeatureId() bool {
	if o != nil && o.FeatureId != nil {
		return true
	}

	return false
}

// SetFeatureId gets a reference to the given int32 and assigns it to the FeatureId field.
func (o *BannerGetRequest) SetFeatureId(v int32) {
	o.FeatureId = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *BannerGetRequest) GetContent() map[string]interface{} {
	if o == nil || o.Content == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BannerGetRequest) GetContentOk() (map[string]interface{}, bool) {
	if o == nil || o.Content == nil {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *BannerGetRequest) HasContent() bool {
	if o != nil && o.Content != nil {
		return true
	}

	return false
}

// SetContent gets a reference to the given map[string]interface{} and assigns it to the Content field.
func (o *BannerGetRequest) SetContent(v map[string]interface{}) {
	o.Content = v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *BannerGetRequest) GetIsActive() bool {
	if o == nil || o.IsActive == nil {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BannerGetRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil || o.IsActive == nil {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *BannerGetRequest) HasIsActive() bool {
	if o != nil && o.IsActive != nil {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *BannerGetRequest) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o BannerGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TagIds != nil {
		toSerialize["tag_ids"] = o.TagIds
	}
	if o.FeatureId != nil {
		toSerialize["feature_id"] = o.FeatureId
	}
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	if o.IsActive != nil {
		toSerialize["is_active"] = o.IsActive
	}
	return json.Marshal(toSerialize)
}

type NullableBannerGetRequest struct {
	value *BannerGetRequest
	isSet bool
}

func (v NullableBannerGetRequest) Get() *BannerGetRequest {
	return v.value
}

func (v *NullableBannerGetRequest) Set(val *BannerGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBannerGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBannerGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBannerGetRequest(val *BannerGetRequest) *NullableBannerGetRequest {
	return &NullableBannerGetRequest{value: val, isSet: true}
}

func (v NullableBannerGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBannerGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
