env: "dev"
server:
  address: "localhost:8888"
postgres:
  dsn: "postgres://banner:postgres1234@postgres:5432/banners?sslmode=disable"
  timeout: 5s
redis:
  address: "redis:6379"
  password: "redis1234"
cache:
  local_size: 1000
  ttl: 5m
service:
  timeout: 50ms
init_timeout: 15s