/*
Сервис баннеров

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BannerIdDeleteRequest struct for BannerIdDeleteRequest
type BannerIdDeleteRequest struct {
	// Идентификаторы тэгов
	TagIds []int32 `json:"tag_ids,omitempty"`
	// Идентификатор фичи
	FeatureId NullableInt32 `json:"feature_id,omitempty"`
	// Содержимое баннера
	Content map[string]interface{} `json:"content,omitempty"`
	// Флаг активности баннера
	IsActive NullableBool `json:"is_active,omitempty"`
}

// NewBannerIdDeleteRequest instantiates a new BannerIdDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBannerIdDeleteRequest() *BannerIdDeleteRequest {
	this := BannerIdDeleteRequest{}
	return &this
}

// NewBannerIdDeleteRequestWithDefaults instantiates a new BannerIdDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBannerIdDeleteRequestWithDefaults() *BannerIdDeleteRequest {
	this := BannerIdDeleteRequest{}
	return &this
}

// GetTagIds returns the TagIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BannerIdDeleteRequest) GetTagIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BannerIdDeleteRequest) GetTagIdsOk() ([]int32, bool) {
	if o == nil || o.TagIds == nil {
		return nil, false
	}
	return o.TagIds, true
}

// HasTagIds returns a boolean if a field has been set.
func (o *BannerIdDeleteRequest) HasTagIds() bool {
	if o != nil && o.TagIds != nil {
		return true
	}

	return false
}

// SetTagIds gets a reference to the given []int32 and assigns it to the TagIds field.
func (o *BannerIdDeleteRequest) SetTagIds(v []int32) {
	o.TagIds = v
}

// GetFeatureId returns the FeatureId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BannerIdDeleteRequest) GetFeatureId() int32 {
	if o == nil || o.FeatureId.Get() == nil {
		var ret int32
		return ret
	}
	return *o.FeatureId.Get()
}

// GetFeatureIdOk returns a tuple with the FeatureId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BannerIdDeleteRequest) GetFeatureIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeatureId.Get(), o.FeatureId.IsSet()
}

// HasFeatureId returns a boolean if a field has been set.
func (o *BannerIdDeleteRequest) HasFeatureId() bool {
	if o != nil && o.FeatureId.IsSet() {
		return true
	}

	return false
}

// SetFeatureId gets a reference to the given NullableInt32 and assigns it to the FeatureId field.
func (o *BannerIdDeleteRequest) SetFeatureId(v int32) {
	o.FeatureId.Set(&v)
}
// SetFeatureIdNil sets the value for FeatureId to be an explicit nil
func (o *BannerIdDeleteRequest) SetFeatureIdNil() {
	o.FeatureId.Set(nil)
}

// UnsetFeatureId ensures that no value is present for FeatureId, not even an explicit nil
func (o *BannerIdDeleteRequest) UnsetFeatureId() {
	o.FeatureId.Unset()
}

// GetContent returns the Content field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BannerIdDeleteRequest) GetContent() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BannerIdDeleteRequest) GetContentOk() (map[string]interface{}, bool) {
	if o == nil || o.Content == nil {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *BannerIdDeleteRequest) HasContent() bool {
	if o != nil && o.Content != nil {
		return true
	}

	return false
}

// SetContent gets a reference to the given map[string]interface{} and assigns it to the Content field.
func (o *BannerIdDeleteRequest) SetContent(v map[string]interface{}) {
	o.Content = v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BannerIdDeleteRequest) GetIsActive() bool {
	if o == nil || o.IsActive.Get() == nil {
		var ret bool
		return ret
	}
	return *o.IsActive.Get()
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BannerIdDeleteRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsActive.Get(), o.IsActive.IsSet()
}

// HasIsActive returns a boolean if a field has been set.
func (o *BannerIdDeleteRequest) HasIsActive() bool {
	if o != nil && o.IsActive.IsSet() {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given NullableBool and assigns it to the IsActive field.
func (o *BannerIdDeleteRequest) SetIsActive(v bool) {
	o.IsActive.Set(&v)
}
// SetIsActiveNil sets the value for IsActive to be an explicit nil
func (o *BannerIdDeleteRequest) SetIsActiveNil() {
	o.IsActive.Set(nil)
}

// UnsetIsActive ensures that no value is present for IsActive, not even an explicit nil
func (o *BannerIdDeleteRequest) UnsetIsActive() {
	o.IsActive.Unset()
}

func (o BannerIdDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TagIds != nil {
		toSerialize["tag_ids"] = o.TagIds
	}
	if o.FeatureId.IsSet() {
		toSerialize["feature_id"] = o.FeatureId.Get()
	}
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	if o.IsActive.IsSet() {
		toSerialize["is_active"] = o.IsActive.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableBannerIdDeleteRequest struct {
	value *BannerIdDeleteRequest
	isSet bool
}

func (v NullableBannerIdDeleteRequest) Get() *BannerIdDeleteRequest {
	return v.value
}

func (v *NullableBannerIdDeleteRequest) Set(val *BannerIdDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBannerIdDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBannerIdDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBannerIdDeleteRequest(val *BannerIdDeleteRequest) *NullableBannerIdDeleteRequest {
	return &NullableBannerIdDeleteRequest{value: val, isSet: true}
}

func (v NullableBannerIdDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBannerIdDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


