/*
Сервис баннеров

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BannerGet201Response struct for BannerGet201Response
type BannerGet201Response struct {
	// Идентификатор созданного баннера
	BannerId *int32 `json:"banner_id,omitempty"`
}

// NewBannerGet201Response instantiates a new BannerGet201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBannerGet201Response() *BannerGet201Response {
	this := BannerGet201Response{}
	return &this
}

// NewBannerGet201ResponseWithDefaults instantiates a new BannerGet201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBannerGet201ResponseWithDefaults() *BannerGet201Response {
	this := BannerGet201Response{}
	return &this
}

// GetBannerId returns the BannerId field value if set, zero value otherwise.
func (o *BannerGet201Response) GetBannerId() int32 {
	if o == nil || o.BannerId == nil {
		var ret int32
		return ret
	}
	return *o.BannerId
}

// GetBannerIdOk returns a tuple with the BannerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BannerGet201Response) GetBannerIdOk() (*int32, bool) {
	if o == nil || o.BannerId == nil {
		return nil, false
	}
	return o.BannerId, true
}

// HasBannerId returns a boolean if a field has been set.
func (o *BannerGet201Response) HasBannerId() bool {
	if o != nil && o.BannerId != nil {
		return true
	}

	return false
}

// SetBannerId gets a reference to the given int32 and assigns it to the BannerId field.
func (o *BannerGet201Response) SetBannerId(v int32) {
	o.BannerId = &v
}

func (o BannerGet201Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BannerId != nil {
		toSerialize["banner_id"] = o.BannerId
	}
	return json.Marshal(toSerialize)
}

type NullableBannerGet201Response struct {
	value *BannerGet201Response
	isSet bool
}

func (v NullableBannerGet201Response) Get() *BannerGet201Response {
	return v.value
}

func (v *NullableBannerGet201Response) Set(val *BannerGet201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBannerGet201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBannerGet201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBannerGet201Response(val *BannerGet201Response) *NullableBannerGet201Response {
	return &NullableBannerGet201Response{value: val, isSet: true}
}

func (v NullableBannerGet201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBannerGet201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


